Jobs
stats4sd/weatherstations_frontend pull request #30
Opened 2020-09-23 16:17 UTC by luciafalcinelli

2020-09-23 18:42 UTC, dave-mills requested changes
Hi Lucia, 

Before we merge this into dev and start testing, there are a few things I think we should address - mainly on explaining what's going on to users with the data maps. (This will double as explaining to Ciara and Carlos!)

When you create data maps in the system, I recall you had decided to modify the DataMapController so that you didn't have to match the form variable name exactly to the database variable name. I see that change on line 125 of the datamap controller. 

Can you update the DataMapCrudController - firstly so that it doesn't use the text from the Soils platform, and second so it's clear that the 'name' references the xlsform variable name and the 'label' is actually the sql field name. 

I also see some other references to the soils platform that we don't need. The relationship between the xlsforms and the datamaps is no longer 1 - many - it's actually reversed! (As we have many data maps for a single form). But for now we can just remove the relationship as it's not relevant atm. 

Cheers,
Dave,

2020-09-24 08:31 UTC, luciafalcinelli commented on database/migrations/2020_09_02_084729_create_new_municipio_table.php
> +        Schema::dropIfExists('new_municipio');
Right, I think it was generated automatically

2020-09-24 12:15 UTC, luciafalcinelli commented on app/Models/Region.php
> +
The regions are at the top levels for the locations, this means they are before of the departamentos. I added the relationship for all the locations.

2020-09-24 12:16 UTC, luciafalcinelli commented on app/Jobs/GetDataFromKobo.php
> +                    $newSubmission['region'] = $departamento->id;
Right, it should be $region->id. I fixed this bug in the last pull.

2020-09-25 09:02 UTC, dave-mills commented on app/Models/Region.php
> +
Cool - thanks!

2020-09-25 10:19 UTC, dave-mills commented on database/migrations/2020_09_02_084729_create_new_municipio_table.php
> +        Schema::dropIfExists('new_municipio');
Yeah, it guesses the table name from the migration name. Can you fix this? (It's not yet fixed in the latest commit I see)

2020-09-25 10:27 UTC, luciafalcinelli commented on database/migrations/2020_09_02_084729_create_new_municipio_table.php
> +        Schema::dropIfExists('new_municipio');
Sorry, I thought that you did. I fixed now

2020-09-25 11:12 UTC, dave-mills commented on app/Http/Controllers/Admin/DataMapCrudController.php
> +                        'name' => 'column_name',
This really isn't enough for someone to know what should go here. The crud controller has references to the soils project with information that is not relevant here; the 'model' variable should not ask about a single data table that the form will populate, as datamaps are per-module, not per-form. 

See my latest pull request for a revised version with detailed labels.

2020-09-25 16:48 UTC, dave-mills approved these changes

2020-09-25 16:48 UTC, merged